Neomake instead Syntastic in NeoVim
zperrault/vimrc.js pull request #7
Opened 2016-09-15 14:44 UTC by renatoagds

**CHANGE LOG**

This PR uses [Neomake](https://github.com/neomake/neomake) instead Syntastic to lint the files, is a big improvement in performance, since Neomake lint the file asynchronous.

2016-09-19 11:24 UTC, zperrault commented
Thank you for this, @renatoagds. I'm going to look at this either today or tomorrow.

2016-09-19 11:32 UTC, zperrault commented on vimrc
> +  let g:neomake_javascript_jshint_maker = {
Is this doing anything if the only enabled maker is eslint?

2016-09-19 11:34 UTC, sloanelybutsurely requested changes
This is really exciting. Do you have time to work on getting this to work for flow as well? If not, I can take over when I get a chance. Would be happy to merge this once we know if that jshint line is required and we can use it for Flow type checking as well.

2016-09-19 16:57 UTC, merged

2016-09-19 16:58 UTC, zperrault commented
@renatoagds I tried this out and it was soooo much faster for both eslint and flow checking. I just couldn't wait so I merged 😄 

Thanks you for this contribution 🙏

2016-09-19 18:34 UTC, renatoagds commented on vimrc
> +  let g:neomake_javascript_jshint_maker = {
@zperrault `neomake` naming is pretty bad, but this one works for `eslint` too :)

2016-09-21 14:02 UTC, davidosomething commented on vimrc
> +  let g:neomake_javascript_jshint_maker = {
that is not true, `g:neomake_javascript_eslint_maker` is used to override the pre-existing eslint maker

2016-09-21 18:24 UTC, renatoagds commented on vimrc
> +  let g:neomake_javascript_jshint_maker = {
@davidosomething you're right! mb, thanks to fix my comment 👍